baseURL = "https://esrlabs.github.io/android-team/"
languageCode = "en-us"
title = "ESR Labs Android Team"
theme = 'hugo-PaperMod-7.0'

[params]
    [params.label]
    icon = "./esr_logo.png"
    text = " Android Team"
    iconHeight = 80