baseURL = "https://esrlabs.github.io/android-team/"
languageCode = "en-us"
title = "Accenture Industry X Android Automotive Team"
theme = 'hugo-PaperMod-7.0'

[params]
    [params.label]
    icon = "./accenture_logo.png"
    text = " Android Automotive Team"
    iconHeight = 27

[markup.goldmark.renderer]
    unsafe= true